language: bash

script:
- mv bank.py files/opt/
- chmod 600 filea.txt
- rsync  -a  -arvce "ssh -i filea.txt -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no " .  packer@52.19.153.94:/tmp/${TRAVIS_BUILD_ID}
- ssh -t -t -i filea.txt -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no packer@52.19.153.94  "( cd /tmp/${TRAVIS_BUILD_ID} ;  packer/build.sh )"

before_install:
- openssl aes-256-cbc -K $encrypted_a64e8c458a8f_key -iv $encrypted_a64e8c458a8f_iv
  -in filea.txt.enc -out filea.txt -d
