language: bash

script:
- mv bank.py files/opt/
- bash packer/build.sh

before_install:
- openssl aes-256-cbc -K $encrypted_a64e8c458a8f_key -iv $encrypted_a64e8c458a8f_iv
  -in filea.txt.enc -out filea.txt -d
